
-- Countries (Auto-generated)
INSERT INTO countries (iso3, name) VALUES ('Lithuania', 'Lithuania') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Brazil', 'Brazil') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Belgium', 'Belgium') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Netherlands', 'Netherlands') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Russian Federation', 'Russian Federation') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Ukraine', 'Ukraine') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Bulgaria', 'Bulgaria') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Czech Republic', 'Czech Republic') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Argentina', 'Argentina') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Romania', 'Romania') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Italy', 'Italy') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('India', 'India') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Mexico', 'Mexico') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Switzerland', 'Switzerland') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Türkiye', 'Türkiye') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Bangladesh', 'Bangladesh') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Slovenia', 'Slovenia') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Spain', 'Spain') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('China', 'China') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Sweden', 'Sweden') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Belarus', 'Belarus') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Japan', 'Japan') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Germany', 'Germany') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('France', 'France') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Kazakhstan', 'Kazakhstan') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Armenia', 'Armenia') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Finland', 'Finland') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Slovakia', 'Slovakia') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Korea, Republic of', 'Korea, Republic of') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Canada', 'Canada') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Pakistan', 'Pakistan') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('South Africa', 'South Africa') ON CONFLICT (iso3) DO NOTHING;
INSERT INTO countries (iso3, name) VALUES ('Hungary', 'Hungary') ON CONFLICT (iso3) DO NOTHING;

-- Nuclear Power Reactors
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Argentina', 3, 1641, 1, 25, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Armenia', 1, 375, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Bangladesh', 0, 0, 2, 2160, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Belarus', 0, 0, 2, 2220, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Belgium', 7, 5930, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Brazil', 2, 1884, 1, 1340, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Bulgaria', 2, 2006, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Canada', 19, 13554, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('China', 48, 45518, 11, 10564, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Czech Republic', 6, 3932, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Finland', 4, 2794, 1, 1600, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('France', 58, 63130, 1, 1630, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Germany', 6, 8113, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Hungary', 4, 1902, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('India', 22, 6255, 7, 4824, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Italy', 0, 0, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Japan', 33, 31679, 2, 2653, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Kazakhstan', 0, 0, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Korea, Republic of', 24, 23172, 4, 5360, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Lithuania', 0, 0, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Mexico', 2, 1552, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Netherlands', 1, 482, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Pakistan', 5, 1318, 2, 2028, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Romania', 2, 1300, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Russian Federation', 38, 28437, 4, 4525, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Slovakia', 4, 1814, 2, 880, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Slovenia', 1, 688, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('South Africa', 2, 1860, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Spain', 7, 7121, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Sweden', 7, 7740, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Switzerland', 4, 2960, 0, 0, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Türkiye', 0, 0, 1, 1114, 0, 2022);
INSERT INTO reactor_statistics (iso3, operational_units, operational_capacity_mw, under_construction_units, under_construction_capacity_mw, shutdown_units, reference_year) VALUES ('Ukraine', 15, 13107, 2, 2070, 0, 2022);