export const WORLD_TOPO_JSON =
    "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";

export const CONTINENT_COLORS: Record<string, string> = {
    Africa: "#10b981",
    Asia: "#f59e0b",
    Europe: "#3b82f6",
    "North America": "#ef4444",
    "South America": "#8b5cf6",
    Oceania: "#14b8a6",
    Antarctica: "#94a3b8",
};

export const NAME_TO_ISO3: Record<string, string> = {
    "United States of America": "USA",
    "United Kingdom": "GBR",
    "South Africa": "ZAF",
    Turkey: "TUR",
    Türkiye: "TUR",
    Spain: "ESP",
    Sweden: "SWE",
    Germany: "DEU",
    Brazil: "BRA",
    Australia: "AUS",
    France: "FRA",
    Finland: "FIN",
    Russia: "RUS",
    "Russian Federation": "RUS",
    China: "CHN",
    India: "IND",
    Japan: "JPN",
    Canada: "CAN",
    Belgium: "BEL",
    Netherlands: "NLD",
    Switzerland: "CHE",
    Argentina: "ARG",
    Armenia: "ARM",
    Belarus: "BLR",
    Bangladesh: "BGD",
    "Czech Republic": "CZE",
    Czechia: "CZE",
    Slovakia: "SVK",
    Slovenia: "SVN",
    Romania: "ROU",
    Ukraine: "UKR",
    Lithuania: "LTU",
    Kazakhstan: "KAZ",
    Mexico: "MEX",
    Pakistan: "PAK",
    "New Zealand": "NZL",
    "Marshall Islands": "MHL",
    Jordan: "JOR",
    Egypt: "EGY",
    "United Arab Emirates": "ARE",
    Iran: "IRN",
    "Iran (Islamic Republic of)": "IRN",
    Indonesia: "IDN",
    Hungary: "HUN",
    Bulgaria: "BGR",
    "Korea, Republic of": "KOR",
    "South Korea": "KOR",
};
